[package]
name = "collate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "collate"
path = "src/bin/collate.rs"

[profile.release]
strip = true
lto = true
opt-level = "z"